Repository aragon/AGPs, pull requests merged in 2018-12, with the labels that each got.

#2 link fix
  AGPs/AGP-1.md
Labels: bug

#3 renaming and link fixes
  AGPs/AGP-0.md
Labels: bug, enhancement

#5 Aragon Flock proposal: Aragon One
  AGPs/A1-2019.md
Labels: Stage IV: Draft Proposal
