Repository aragon/AGPs, pull requests merged in 2019-07, with the labels that each got.

#70 AGP-70: Decentralize Nest
  AGPs/AGP-70.md
Labels: Stage IV: Final Proposal

#66 AGP-66: Panvala Launch Partnership
  AGPs/AGP-66.md
Labels: Stage IV: Final Proposal

#73 Create AGP-73: Flock Funding for Autark
  AGPs/AGP-73.md
Labels: Stage IV: Final Proposal

#64 AGP-64: Support Quiet Ending Voting
  AGPs/AGP-64.md
Labels: Stage IV: Final Proposal

#59 Create AGP-59: Community Review Period
  AGPs/AGP-59.md
Labels: Stage IV: Final Proposal

#74 AGP-74: Single-purpose native mobile app for Aragon voting
  AGPs/AGP-74.md
Labels: Stage IV: Final Proposal

#67 AGP-67: 2019 Aragon Events Multisig Budget
  AGPs/AGP-67.md
Labels: Stage IV: Final Proposal

#72 AGP-72: Frame Finance Proposal
  AGPs/AGP-72.md
Labels: Stage IV: Final Proposal

#75 AGP-75: The Aragon Governance Survey Process
  AGPs/AGP-75.md
Labels: Stage IV: Final Proposal

#61 AGP-61: Modify Aragon Network Fiscal Year
  AGPs/AGP-61.md
Labels: Stage IV: Final Proposal

#78 Update AGP status
  AGPs/AGP-59.md
  AGPs/AGP-61.md
  AGPs/AGP-64.md
  AGPs/AGP-66.md
  AGPs/AGP-67.md
  AGPs/AGP-70.md
  AGPs/AGP-71.md
  AGPs/AGP-72.md
  AGPs/AGP-73.md
  AGPs/AGP-74.md
  AGPs/AGP-75.md
Labels: Stage V: ANT Vote

#58 Pull request for Meta AGP-59: Community Review Period
  AGPs/AGP-1.md
  images/AGP-1/AGP-1-1-1-0.png
  images/AGP-1/AGP-1_1-2-1.png
Labels: Meta PR
